### ISSUE TITLE
OpenGL dependency

### ISSUE THREAD

**Issue by nh2** [haskell-openal/ALUT#1]
Hi,

Does ALUT really need the OpenGL dependency?

From my short look at it it seems it only uses it for StateVars - this should be easy to extract. If I read that right, you even made a package for this (http://hackage.haskell.org/package/StateVar-1.0.0.0/docs/Data-StateVar.html) - why not use it?

**Comment by phaazon** [comment]
I think we should re-open this, and correctly adress the issue; i.e. creating common packages for `OpenGL` and `OpenAL`. This is insane that `OpenAL` depends on `OpenGL`.

**Comment by svenpanne** [comment]
I would be more than happy to remove the StateVar/ObjectName/Tensor stuff from the OpenGL package. Separate packages for these are already on Hackage for quite some time. Perhaps you should raise this issue on the libraries mailing list again.

I'm not sure how alive the Haskell Platform is nowadays, I have the feeling that people are moving away from it and towards e.g. Stackage, but that is just a gut feeling. So the "political pressure" might not be so high anymore.

**Comment by phaazon** [comment]
What are those used for then? I know StateVar and its `($=)` operator. If you think we can drop them, then go for it.

I don’t use Haskell Platform, but MingGHC for Windows, and bare ghc / cabal-install for archlinux. Still, I think we should do something for `OpenAL` :(.

**Comment by svenpanne** [comment]
I don't fully understand what you mean by "What are those used for then?". OpenAL needs the functionality of all 3 packages StateVar/ObjectName/Tensor if we remove the dependency on OpenGL. But this again would mean that exactly the features of these 3 packages have to be removed from the OpenGL package itself and made dependencies instead. Otherwise using the OpenGL and OpenAL packages together wouldn't work at all, at least not without heavy qualifications, which would defeat a lot of use cases.

I've found the last discussion on the libraries list: https://mail.haskell.org/pipermail/libraries/2014-October/023976.html There was basically no outcome at all, but perhaps you could revive that thread, adding another use case in addition to the ones mentioned by Edward? Maybe we can avoid bikeshedding discussions this time... :unamused:

**Comment by phaazon** [comment]
Ok, but why `OpenAL` doesn’t use the extern packages already?

**Comment by svenpanne** [comment]
As I said above: You would have name clashes for tons of things (e.g. StateVar, $=, ObjectName, etc.) if OpenGL and OpenAL were used together. I consider this a no-go, so I'll only remove the dependency from OpenGL if OpenGL itself will change accordingly. From a technical standpoint this is the right thing, anyway, and this is how it was initially. I (and obviously ekmett) would be happy if this happens, so please bring this up on the libraries list.
